FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py .
COPY GateBooks/ GateBooks/
COPY route/ route/
COPY pipeline/ pipeline/
COPY service/ service/
COPY repository/ repository/

EXPOSE 8000

COPY backend-start.sh .
RUN chmod +x backend-start.sh

CMD ["./backend-start.sh"]
