FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py .
COPY route/ route/
COPY pipeline/ pipeline/
COPY service/ service/
COPY repository/ repository/

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "route.api:app", "--host", "0.0.0.0", "--port", "8000"]
