apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: backend
        image: ghcr.io/priyanjanmitra/rag_wiki_qa-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_URL
          value: "http://ollama:11434"
        volumeMounts:
        - name: index-data
          mountPath: /app/index
      volumes:
      - name: index-data
        persistentVolumeClaim:
          claimName: rag-index
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-index
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
